### ISSUE TITLE
Plugin does not accept uints for publishing

### ISSUE THREAD

**Issue by IRCody** [intelsdi-x/snap-plugin-publisher-mysql#16]
Because of the implementation of [interfaceToString()](https://github.com/intelsdi-x/snap-plugin-publisher-mysql/blob/master/mysql/mysql.go#L164) uints passed in as Data will result in an unsupported type error. 

Some of the procfs plugins use uints for there data. See: [meminfo](https://github.com/intelsdi-x/snap-plugin-collector-meminfo), [processes](https://github.com/intelsdi-x/snap-plugin-collector-processes).

Also see: [snap-issue-#894](https://github.com/intelsdi-x/snap/issues/894)

**Comment by Lactem** [comment]
I have a [fix ready to be tested](https://github.com/Lactem/snap-plugin-publisher-mysql/tree/uint_support) as soon as the [new metric schema PR](https://github.com/intelsdi-x/snap-plugin-publisher-mysql/pull/17) goes through (to avoid updating metric schema and fixing this problem in the same PR).

**Comment by IRCody** [comment]
@Lactem: #17 has been merged.

**Comment by mjbrender** [comment]
@Lactem or @IRCody - have someone else running into this error. I'll ask him to explain further.

**Comment by acwrenn** [comment]
I have been running Snap 0.14.0 with mySQL Publisher 7 and running into the unsupported type error for every collector I've tried (psutils, df) except for the mock ones.

**Comment by Lactem** [comment]
@lynxbat  @acwrenn Is this issue still happening when using the most recent version (with #18 merged)?

**Comment by katarzyna-z** [comment]
I've tested snap with df collector and mysql publisher and it works without errors. I used versions from following commits:
- [snap commit](https://github.com/intelsdi-x/snap/commit/93eb9097f701fe490a833066e6c83667816be4e9)
- [mysql commit](https://github.com/intelsdi-x/snap-plugin-publisher-mysql/commit/9c357297a93066ccb145bdd9d7b8ac352a94a473),
- [df commit](https://github.com/intelsdi-x/snap-plugin-collector-df/commit/411e248ccf2c3897548a08336470b6390e9f6e68).

**Comment by IRCody** [comment]
@lynxbat: Closing this issue again since @katarzyna-z was unable to reproduce and no response from anyone saying it's still an issue. Feel free to re-open if you are still having the issue.
