### ISSUE TITLE
Incorrect Copyright?

### ISSUE THREAD

**Issue by Lactem** [intelsdi-x/snap-plugin-publisher-mysql#22]
[The most recent commit](https://github.com/intelsdi-x/snap-plugin-publisher-mysql/commit/d62c5f5a398e391f5f3e6575fad970d1ea5e6c52) changes the copyright in the [LICENSE file ](https://github.com/intelsdi-x/snap-plugin-publisher-mysql/blob/d62c5f5a398e391f5f3e6575fad970d1ea5e6c52/LICENSE#L190)into a template (it used to be [copyright Intel](https://github.com/intelsdi-x/snap-plugin-publisher-mysql/blob/5b34133500453590ac8f0c570c4deb783c125ce9/LICENSE#L190)).

Also, some files still have 2015 instead of 2016 for their copyright headers.

**Comment by kindermoumoute** [comment]
> APPENDIX: How to apply the Apache License to your work.

In this LICENSE file, the APPENDIX is an optional part that give a template to use for source files. 

> Also, some files still have 2015 instead of 2016 for their copyright headers.

The year of creation of the file is sufficient.
